version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: pm_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./product-management-backend
    container_name: pm_backend
    ports:
      - "5000:5000"
    env_file:
      - ./product-management-backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./product-management-frontend
    container_name: pm_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
